### PR TITLE
Rewrite of Documentation

### PR DESCRIPTION
**Pull request by PadowYT2**
Example page: https://test.padow.ru

**This update will be including v2 pre13 and other pull requests in other repo's (going to be linked soon)**

Other issues and pulls:
NamelessMC/Nameless#2549
NamelessMC/Nameless-Link#265
NamelessMC/Nameless-Installer#11
NamelessMC/Nameless-Plugin#203

**Note: Before releasing, firstly do all other requests/issues (except nameless)**

### CODE REVIEW

**Comment by Fjuro** [comment]
Does it have a web editor and language system?

**Comment by PadowYT2** [comment]
About language system, on docs.namelessmc.com it is bad, why? But it can be made
* Outdated
* Some of them not even started

About web editor, it does not exist but, it is not that very a big of a deal, why?
* Docs don't update like once a day
* And easier updating files, because pull requests, others can create/fix/remove things

**Comment by Fjuro** [comment]
Well the language system is one of the reasons we switched to wiki.js
And I don't think wiki.js is bad either, it has a great design and many features

**Comment by PadowYT2** [comment]
Half of the languages on `docs.namelessmc.com` are not even started, 45% is pre10, 5% is pre9
About design, looks kinda not that good, in this wiki, many things can be included

**Comment by tadhgboyle** [comment]
What are the reasons we should switch from our Wiki.js instance to this? 
I don’t have any issues with wiki.js

**Comment by PadowYT2** [comment]
About `wiki.js` the desing looks kinda good kinda bad, there are no tabs for making like `Link Bot`, `Website` and `Plugin`, making it in the sidebar is not good, too many links, it is better to have tabs
Second, there are no tips, danger, warning (red, blue, orange boxes)
Third, tabs for webservers (example), to not make it in the same page, keeping it in tabs

**Comment by Fjuro** [comment]
1) The design looks in my opinion maybe even better than the Pterodactyl wiki, it's using Material Design which still looks good.
2) The sidebar is enough, there are dividers and icons which make it look better
3) There are tips, we just haven't used them
4) I don't really know what tabs are you talking about

**Comment by PadowYT2** [comment]
Navbar tabs
image
Webserver tabs
image

**Comment by Fjuro** [comment]
Wiki.js does have those "webserver" tabs too

**Comment by PadowYT2** [comment]
> 2. The sidebar is enough, there are dividers and icons which make it look better

There will be a lot of items, it needs to be organized, but here it easier actually to keep in tabs

Now it is your choice to accept/decline the PR

If gets declined, I'll make changes from this wiki to wiki.js
   What I need:
* How to make those tabs
* How to make tips

If gets accepted, then it gets accepted

**Comment by Fjuro** [comment]
Tabs: https://docs.requarks.io/en/editors/markdown#content-tabs
Tips:
```
> Some text
> More text if you want
{.is-info/warning/danger...}
```

**Comment by PadowYT2** [comment]
So this can be closed?

**Comment by Fjuro** [comment]
Probably, I don't think they would want to change it - maybe ask on Discord but I'm for keeping wiki.js

**Comment by PadowYT2** [comment]
https://canary.discord.com/channels/246705793066467328/246705793066467328/911836724517281822

**Comment by Fjuro** [comment]
Hey, I don't think this is going anywhere so I would just suggest to contact Derkades to give you access to the current documentation so there aren't two of them

**Comment by PadowYT2** [comment]
Yep, this won't be merged, but this will be migrated to wiki.js

**Pull request closed without merging**
